name: Build to Docker Hub

on:
  release:
    types: [published]
    # branches:
    # - master
  push:
    branches:
    - 06-03-22/build-on-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Build Docker Image from ${{ github.event.release.name }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          TAG: ${{ github.event.release.tag_name }}
        run: echo "$GITHUB_CONTEXT >>> TAG $TAG"
