name: Build to Docker Hub

on:
  release:
    types: [published]
    # branches:
    # - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
